openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: https://api.36node.com{basePath}
    description: The production API server
    variables:
      basePath:
        default: /dushuli/v0
paths:
  /books:
    get:
      summary: List all books
      operationId: listBooks
      tags:
        - books
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time
          required: false
          schema:
            type: integer
            format: int32
            default: 100
        - name: sort
          in: query
          description: Sort Name
          required: false
          schema:
            type: string
            default: updatedAt
        - name: order
          in: query
          description: Sort order(1 || -1)
          required: false
          schema:
            type: string
            default: -1
        - name: date_gt
          in: query
          description: Return Books Date greater than given date
          required: false
          schema:
            type: date
        - name: date_lt
          in: query
          description: Return Books Date less than given date
          required: false
          schema:
            type: date
      responses:
        "200":
          description: A paged array of books
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Books"
              examples:
                default:
                  value: |
                    [
                      {
                        "date": "2018-12-24T05:32:40.000Z",
                        "holiday": "春节1",
                        "solarTerm": "春分1",
                        "book": "一本书2",
                        "author": "作者2",
                        "summary": "一些summary123",
                        "content": "<p>dasdhadd3123<a>dasdad</a></p>",
                        "updatedAt": "2018-12-24T05:59:02.250Z",
                        "createdAt": "2018-12-24T05:59:02.250Z",
                        "id": "5c2075a6fe46ab69eec17de0"
                      },
                      {
                        "date": "2018-12-24T05:30:40.000Z",
                        "holiday": "春节2",
                        "solarTerm": "春分2",
                        "book": "一本书3",
                        "author": "作者3",
                        "summary": "一些summary1232344",
                        "content": "<p>dasdhadd3123<b>dasdad</b></p>",
                        "updatedAt": "2018-12-24T05:59:12.250Z",
                        "createdAt": "2018-12-24T05:59:12.250Z",
                        "id": "5c2075a6fe46ab69eec17de1"
                      }
                    ]
        "401":
          $ref: "#/components/responses/Unauthorized"
        "500":
          $ref: "#/components/responses/InternalError"

    post:
      summary: Create a book
      operationId: createBook
      tags:
        - books
      requestBody:
        description: book to add to the store
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewBook"
            examples:
              default:
                value: |
                  {
                    "date": "2018-12-24T13:32:40+08:00",
                    "holiday": "春节1",
                    "solarTerm": "春分1",
                    "book": "一本书2",
                    "author": "作者2",
                    "summary": "一些summary123",
                    "content": "<p>dasdhadd3123<b>dasdad</b></p>"
                  }
      responses:
        "201":
          description: The Book created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Books"
              examples:
                default:
                  value: |
                    {
                      "date": "2018-12-24T13:32:40+08:00",
                      "holiday": "春节1",
                      "solarTerm": "春分1",
                      "book": "一本书2",
                      "author": "作者2",
                      "summary": "一些summary123",
                      "content": "<p>dasdhadd3123<b>dasdad</b></p>",
                      "id": "5c2075a6fe46ab69eec17de1"
                    }
        "401":
          $ref: "#/components/responses/Unauthorized"
        "500":
          $ref: "#/components/responses/InternalError"

  /books/{bookId}:
    get:
      summary: Find book by id
      operationId: showBookById
      tags:
        - books
      parameters:
        - name: bookId
          in: path
          required: true
          description: The id of the book to retrieve
          schema:
            type: string
      responses:
        "200":
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Books"
              examples:
                default:
                  value: |
                    {
                      "date": "2018-12-24T13:32:40+08:00",
                      "holiday": "春节1",
                      "solarTerm": "春分1",
                      "book": "一本书2",
                      "author": "作者2",
                      "summary": "一些summary123",
                      "content": "<p>dasdhadd3123<b>dasdad</b></p>",
                      "id": "5c2075a6fe46ab69eec17de1"
                    }
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalError"
    delete:
      description: deletes a single book based on the ID supplied
      operationId: deleteBookById
      tags:
        - books
      parameters:
        - name: bookId
          in: path
          description: ID of book to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "204":
          description: book deleted
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalError"
    put:
      description: update a single book based on the ID supplied
      operationId: updateBookById
      tags:
        - books
      parameters:
        - name: bookId
          in: path
          description: ID of book to update
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: book to update to the store
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewBook"
            examples:
              default:
                value: |
                  {
                    "date": "2018-12-24T13:32:40+08:00",
                    "holiday": "春节1",
                    "solarTerm": "春分1",
                    "book": "一本书2",
                    "author": "作者2",
                    "summary": "一些summary123",
                    "content": "<p>dasdhadd3123<b>dasdad</b></p>"
                  }
      responses:
        "200":
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Books"
              examples:
                default:
                  value: |
                    {
                      "date": "2018-12-24T13:32:40+08:00",
                      "holiday": "春节1",
                      "solarTerm": "春分1",
                      "book": "一本书2",
                      "author": "作者2",
                      "summary": "一些summary123",
                      "content": "<p>dasdhadd3123<b>dasdad</b></p>",
                      "id": "5c2075a6fe46ab69eec17de1"
                    }
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalError"

security:
  - bearerAuth: []

components:
  responses:
    NoContent:
      description: The resource was deleted successfully.
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Err"
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Err"
    InternalError:
      description: unexpected error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Err"
  schemas:
    Books:
      required:
        - date
        - book
        - content
      properties:
        date: 
          type: date
        holiday:
          type: string
        solarTerm:
          type: string
        book:
          type: string
        author:
          type: string
        summary:
          type: string
        content:
          type: string
        audio:
          type: string
    NewBook:
      required:
        - date
        - book
        - content
      properties:
        date: 
          type: date
        holiday:
          type: string
        solarTerm:
          type: string
        book:
          type: string
        author:
          type: string
        summary:
          type: string
        content:
          type: string
        audio:
          type: string
    Err:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message

  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT
