openapi: "3.0.0"
info:
  version: 1.0.0
  title: Dushuli
  description: "读书历CRUD服务"
  license:
    name: MIT
servers:
  - url: https://api.36node.com{basePath}
    description: The production API server
    variables:
      basePath:
        default: /dushuli/v0
paths:
  /wechat/payment:
    post:
      summary: initiate a payment process
      operationId: createPayment
      tags:
        - wechat
      requestBody:
        description: payment info
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreatePaymentBody"
      responses:
        "200":
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreatePaymentResponse"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalError"

  /wechat/signature:
    get:
      summary: get wechat js sdk signature
      operationId: getSignature
      tags:
        - wechat
      parameters:
        - name: url
          in: query
          description: 调用 jssdk 的网页链接
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetSignatureResponse"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalError"
  /wechat/payment-callback:
    post:
      summary: wechat pay callback
      operationId: wechatPayCallback
      tags:
        - wechat
      requestBody:
        description: wechat pay callback data
        required: true
        content:
          application/json:
              schema:
                $ref: "#/components/schemas/WechatPayCallback"
      responses:
        "200":
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WechatPayCallbackResponse"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalError"
        


      
security:
  - bearerAuth: []

components:
  responses:
    NoContent:
      description: The resource was deleted successfully.
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Err"
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Err"
    InternalError:
      description: unexpected error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Err"
  schemas:
    CreatePaymentBody:
      type: object
      required:
        - openid
      properties:
        openid:
          type: string
          description: 付款用户的openid
        sandbox:
          type: boolean
          description: 是否是沙盒模式
    
    CreatePaymentResponse:
      type: object
      properties:
        appid:
          type: string
          description: 公众号 appid
          example: "wx8888888888888888"
        timeStamp: 
          type: string
          description: 时间戳
          example: "1414561699"
        nonceStr:
          type: string
          description: 随机字符串
          example: "5K8264ILTKCH16CQ2502SI8ZNMTM67VS"
        package:
          type: string
          description: 订单详情扩展字符串
          example: "prepay_id=123456789"
        signType:
          type: string
          description: 签名方式
          example: "MD5"
        paySign:
          type: string
          description: 签名
          example: "C380BEC2BFD727A4B6845133519F3AD6"

    GetSignatureResponse:
      type: object
      properties:
        debug:
          type: boolean
        appId:
          type: string
          description: 公众号 appid
          example: "wx8888888888888888"
        timestamp:
          type: string
          description: 时间戳
          example: "1414561699"
        nonceStr:
          type: string
          description: 随机字符串
          example: "5K8264ILTKCH16CQ2502SI8ZNMTM67VS"
        signature:
          type: string
          description: 签名
          example: "5bfc8633f9c2127508296408c64f99068ad9dcb5"
        jsApiList:
          type: array
          items:
            type: string
          description: js api 列表
          example: [
            "checkJsApi",
            "onMenuShareTimeline",
            "onMenuShareAppMessage",
            "onMenuShareQQ",
            "onMenuShareWeibo",
            "onMenuShareQZone",
            "chooseImage",
            "previewImage",
            "uploadImage",
            "startRecord",
            "stopRecord",
            "onVoiceRecordEnd",
            "playVoice",
            "pauseVoice",
            "stopVoice",
            "onVoicePlayEnd",
            "uploadVoice",
            "downloadVoice",
            "translateVoice",
            "getNetworkType",
            "openLocation",
            "getLocation",
            "startSearchBeacons",
            "stopSearchBeacons",
            "onSearchBeacons",
            "closeWindow",
            "hideMenuItems",
            "showMenuItems",
            "hideAllNonBaseMenuItem",
            "showAllNonBaseMenuItem",
            "scanQRCode",
            "openProductSpecificView",
            "chooseCard",
            "addCard",
            "openCard",
            "chooseWXPay"
          ]
        
    WechatPayCallback:
      type: object
      properties:
        appid:
          type: string
          description: 公众号 appid
          example: "wx8888888888888888"
    
    WechatPayCallbackResponse:
      type: string

    Err:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message

  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT
